### ISSUE TITLE
Detailed Usage Guide

### ISSUE THREAD

**Issue by xfryser** [sambitpoddar/ninjaprobe#1]
Can you make the usage guide a bit more detailed for better reference purpose? I was a bit confused about the proxies. As I tried to use a proxy but received an error. But without the proxy, it worked wonderfully.

**Comment by sambitpoddar** [comment]
Please provide an image or specifically mention the ErrorType you are facing.

**Comment by sambitpoddar** [comment]
Please provide specific details like ErrorType or an image of the error.

**Comment by sambitpoddar** [comment]
Please provide specific details like ErrorType or an image of the error.
